export const colors = {
  primary: "#1A4D55",
  pink: "#FFC7EE",
  lemon: "#AEEBAD",
  lightBlue: "#A1D8FF",
  lightBg: "#3C696E",
  switchOff: "#CBCED8",
  inputBg: "#F5F7FB",
  todoText: "#6B6A6F",
  blackText: "#000",
  whiteText: "#fff",
};
export const todoData = [
  {
    id: "plus",
    isPlus: true,
    bg: colors.lightBg,
    todo: "update a cop of the last article",
    sharedWith: "shred with amanda",
  },
  {
    id: "2",
    title: "Blog",
    count: "21",
    bg: colors.pink,
    todo: "update a cop of the last article",
    sharedWith: "shred with amanda",
  },
  {
    id: "3",
    title: "Personal",
    count: "12",
    bg: colors.lightBlue,
    todo: "update a cop of the last article",
    sharedWith: "shred with amanda",
  },
  {
    id: "4",
    title: "Personal",
    count: "12",
    bg: colors.lemon,
    todo: "update a cop of the last article",
    sharedWith: "shred with amanda",
  },
];
